language: c
env:
  global:
    - PROJECT_ROOT="$(pwd)"
    - CI_SCRIPTS="$PROJECT_ROOT/.ci"
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
    - secure: "jOnJJUc9bBrdghXUGDQktV8pslv2DMIUS8Xy3E5UWs2Qy+vpuFY2gY3NCrd08XBlrpOOaodoG/eD8jFcq9y060i7fe5XM7mQL9oiVx+r6QT/of7tEA173EGxOazoaoQoiZDPPWT3ePAXx8jCQdDcVEKYBlxu9CKBz3drlGUM7bk="
  matrix:
    - CI_TARGET=clang-asan
    - CI_TARGET=gcc-ia32
    - CI_TARGET=gcc-unittest
    - CI_TARGET=clint
    - CI_TARGET=api-python
    - CI_TARGET=coverity
before_install:
  # Adds user to a dummy group.
  # That allows to test changing the group of the file by `os_fchown`.
  - sudo groupadd chown_test
  - sudo usermod -a -G chown_test ${USER}
script:
  # This will pass the environment variables down to a bash process which runs
  # as $USER, while retaining the environment variables defined and belonging
  # to secondary groups given above in usermod.
  - sudo -E su ${USER} -c "sh -e \"${CI_SCRIPTS}/${CI_TARGET}.sh\""
